### ISSUE TITLE
Link leads nowhere

### ISSUE THREAD

**Issue by robertleeplummerjr** [IonicaBizau/I-Love-Octocats#17]
From your initial page, it leads nowhere: https://github.com/IonicaBizau/I-Love-Octocats/blob/happy2016/CONTRIBUTING.md

**Comment by IonicaBizau** [comment]
@robertleeplummerjr Thanks for heads-up! :+1: 

Honestly, I was waiting for that person to report this. :joy:
I generate these files using [`blah`](https://github.com/IonicaBizau/blah).
