### ISSUE TITLE
Octocat tunnel

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/I-Love-Octocats#3]
![image](https://cloud.githubusercontent.com/assets/2864371/6575740/369a9e76-c73a-11e4-8700-78a89621a08c.png)

**Comment by GhitaB** [comment]
Test.

**Comment by IonicaBizau** [comment]
Hello World

**Comment by IonicaBizau** [comment]
Foo

**Comment by IonicaBizau** [comment]
Bar

**Comment by IonicaBizau** [comment]
Another foo

**Comment by IonicaBizau** [comment]
Another bar

**Comment by IonicaBizau** [comment]
Foo

**Comment by IonicaBizau** [comment]
Bar

**Comment by IonicaBizau** [comment]
foo

**Comment by IonicaBizau** [comment]
foo

**Comment by IonicaBizau** [comment]
@izuzak [Pretty neat, right?](https://github.com/evilsuperizuzak) They :heart:  you! :smile: :star2: :trollface: :fireworks:

**Comment by IonicaBizau** [comment]
@izuzak We should celebrate somehow almost one year since we met in Zurich. :smile:
